name: Trigger auto deployment for delivery-point

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/delivery-point-AutoDeployTrigger-31b75737-4596-4b26-84aa-36a6261bfcbb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DELIVERYPOINT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DELIVERYPOINT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DELIVERYPOINT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: bananay.azurecr.io
          registryUsername: ${{ secrets.DELIVERYPOINT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DELIVERYPOINT_REGISTRY_PASSWORD }}
          containerAppName: delivery-point
          resourceGroup: Bananay
          imageToBuild: bananay.azurecr.io/delivery-point:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


